const express = require("express")
const connectDB = require("./config/db.js")
const cors = require("cors")
const studentRouter = require("./routes/studentRoute.js")
const courseRouter = require("./routes/courseRoute.js")
const userRoute = require("./routes/userRoute.js")
require("dotenv").config()
const port = process.env.PORT || 5000
const app = express()
app.use(cors())
connectDB()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use("/api/v1/student",studentRouter)
app.use("/api/v1/course",courseRouter)
app.use("/api/v1/user",userRoute)
app.listen(port,()=>{
    console.log(`server run on port ${port}`)
})